
关键字：`noexcept`

----

C++ 相比较于C而言定义了一整套完整的异常处理机制，C++11将异常声明简化成以下两种情况，并使用 `noexcept` 对行为进行限制：

1. 函数可能抛出任何异常；
```cpp
void may_throw();
```
2. 函数不能抛出任何异常；
```cpp
void no_throw() noexcept;
```

被 `noexcept` 修饰过的函数如果抛出异常，编译器就会使用 `std::terminate()` 来立即终止程序运行，也可以作为一个表达式当无异常时返回 `true`，有异常时返回 `false`。

```cpp
void may_throw(){
    throw true;
};

auto non_block_throw = []{
    may_throw();
};

void no_throw() noexcept {
    return ;
};

auto block_throw = []() noexcept{
    no_throw();
};

int main(){
    std::cout << std::boolalpha 
        << noexcept(may_throw()) << std::endl
        << noexcept(no_throw()) << std::endl
        << noexcept(non_block_throw()) << std::endl
        << noexcept(block_throw()) << std::endl;
    return 0;
};
```

`noexcept` 修饰完的一个函数还可以起到封锁异常扩散的作用，如果内部产生了异常，外部也不会触发：
